[build]
  command = "npm run build"
  functions = "functions/"
[[redirects]]
  from = "/api/youtube"
  to = "/.netlify/functions/youtube"
[[plugins]]
package = "netlify-plugin-inline-functions-env"
   [plugins.inputs]
    include = ["GOOGLE_PRIVATE_KEY"]